---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: debian-9
    image: debian:9
provisioner:
  name: ansible
  inventory:
    links:
      group_vars: ../default/inventory/group_vars
  lint:
    name: ansible-lint
scenario:
  name: github
verifier:
  name: testinfra
  lint:
    name: flake8
